In [5]:
import numpy as np


In [10]:
array2d=np.array([[1,2,3],[4,5,6]])
array2d

print("Dimensions:",array2d.ndim)
print("Shape:",array2d.shape)

np.linspace

Dimensions: 2
Shape: (2, 3)


<function linspace at 0x7f5e80286030>

In [11]:
motu= np.linspace(2,5,5)
#Calculating step size = (5 - 2) / (4 - 1) = 4 / 3 = 1.33333333
#next value=previous + step_size
print(motu)

[2.   2.75 3.5  4.25 5.  ]


In [22]:
print(np.random.randint(1, 10, size=(4, 4)))
print(np.eye(4))
print(np.full((2, 2), 7))

[[1 3 4 1]
 [4 5 9 9]
 [8 9 5 5]
 [2 2 8 2]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 7]
 [7 7]]


In [26]:
data=np.array([22,33,44,55])
np.savetxt('output.txt',data,delimiter=',', )

In [33]:

my_array=np.array([[1,2,3],[4,5,6],[7,8,9]])

my_array[my_array<2]

array([1])