In [43]:
# Question 1
import pandas as pd
import numpy as np
import os 
product_A_price=10
product_B_price=20
product_C_price=15

Sold_A=100
Sold_B=50
Sold_C=75


print("Revenue from Product A:$",product_A_price*Sold_A)
print("Revenue from Product B:$",product_B_price*Sold_B)
print("Revenue from Product C:$",product_C_price*Sold_C)
print("Total Revenue:$",product_A_price*Sold_A+product_B_price*Sold_B+product_C_price*Sold_C)



Revenue from Product A:$ 1000
Revenue from Product B:$ 1000
Revenue from Product C:$ 1125
Total Revenue:$ 3125


In [44]:
#Question 2
import random
import statistics

financial_data_path="financial_data"

if not os.path.exists(financial_data_path):
    os.makedirs(financial_data_path)

My_dictionary={}

year=2022
day=1
month=1
Revenue=30000
Expenses=20000

My_dictionary['Date']=[]
My_dictionary['Revenue']=[]
My_dictionary['Expenses']=[]

l=0
while(l<=10):
    My_dictionary['Date'].append(f"{year}-{day}-{month}")
    My_dictionary['Revenue'].append(f"{Revenue}")
    My_dictionary['Expenses'].append(f"{Expenses}")
    day=random.randint(1,31)
    month=random.randint(1,13)
    Revenue=random.randrange(30000,90000,10000)
    Expenses=random.randrange(30000,80000,6500)
    l+=1

My_data_frame=pd.DataFrame(My_dictionary)
print(My_data_frame)
with open(os.path.join(financial_data_path,"financial_data.csv") , "w") as file:
    My_data_frame.to_csv(file,index=False)
    

#Profit for each month Revenue - Expense 
Revenue_list=[]
Revenue_list.extend(My_data_frame['Revenue'])


Expenses_list=[]
Expenses_list.extend(My_data_frame['Expenses'])
Profit_list=[]

for i in  range(len(My_data_frame['Date'])):
        Profit_list.append(int(Revenue_list[i]) - int(Expenses_list[i]))


#I Added another column of profit to the dataframe just to make it easy to understand
print("\nProfit column ADDED!!!!")
My_dictionary['Profit']=Profit_list
My_data_frame=pd.DataFrame(My_dictionary)
print(My_data_frame)
with open(os.path.join(financial_data_path,"financial_data.csv") , "w") as file:
    My_data_frame.to_csv(file,index=False)

total=0
num=0
for i in Profit_list:
    if(int(i)>0):
        total+=int(i)
        num+=1

average_profit=total/num

print("It is the average of Profit only not the loss which are negative values")
print("Average Profit:",average_profit)


          Date Revenue Expenses
0     2022-1-1   30000    20000
1    2022-23-5   60000    36500
2    2022-12-1   80000    30000
3    2022-13-1   70000    49500
4   2022-26-10   30000    49500
5    2022-7-12   40000    49500
6   2022-16-12   40000    75500
7     2022-1-9   50000    43000
8    2022-7-11   60000    75500
9   2022-20-12   80000    36500
10   2022-15-9   30000    30000

Profit column ADDED!!!!
          Date Revenue Expenses  Profit
0     2022-1-1   30000    20000   10000
1    2022-23-5   60000    36500   23500
2    2022-12-1   80000    30000   50000
3    2022-13-1   70000    49500   20500
4   2022-26-10   30000    49500  -19500
5    2022-7-12   40000    49500   -9500
6   2022-16-12   40000    75500  -35500
7     2022-1-9   50000    43000    7000
8    2022-7-11   60000    75500  -15500
9   2022-20-12   80000    36500   43500
10   2022-15-9   30000    30000       0
It is the average of Profit only not the loss which are negative values
Average Profit: 25750.0


In [75]:
#Question #3

Student_data=np.random.randint(30,90,(3,3))

print(Student_data)

Avg_math=0
Avg_science=0
Avg_english=0

for i in Student_data:
        Avg_math+=i[0]
        Avg_science+=i[1]
        Avg_english+=i[2]
        
print("Math Average:",Avg_math/3)
print("English Average:",Avg_english/3)
print("Science Average:",Avg_science/3)

print("Average Score overall subject:",(Avg_science+Avg_english+Avg_math)/9)

#Top student
Student_1_avg=0
Student_2_avg=0
Student_3_avg=0

Student_1_avg+=(Student_data[0][0]+Student_data[0][1]+Student_data[0][2])
Student_2_avg+=(Student_data[1][0]+Student_data[1][1]+Student_data[1][2])
Student_3_avg+=(Student_data[2][0]+Student_data[2][1]+Student_data[2][2])
    

Comparing=[]
Comparing.extend([Student_1_avg/3,Student_2_avg/3,Student_3_avg/3])
print("Average Marks of Each student of all subject:",end=" ")
print(Comparing)
Maximum_average=max(Comparing)
print("Student:",Comparing.index(Maximum_average)+1," Scoured Maximum Average :",Maximum_average)

Subjects_list=[]
Subjects_list.extend([Avg_math,Avg_english,Avg_science])

Max_Subj_average_num=max(Subjects_list)

if(Subjects_list.index(Max_Subj_average_num) == 0):
    print("Student has improve highly in Math")
elif(Subjects_list.index(Max_Subj_average_num) == 1):
    print("Student has improve highly in English") 
elif(Subjects_list.index(Max_Subj_average_num) == 2):
    print("Student has improve highly in Science")

[[81 74 35]
 [87 31 87]
 [43 47 47]]
Math Average: 70.33333333333333
English Average: 56.333333333333336
Science Average: 50.666666666666664
Average Score overall subject: 59.111111111111114
Average Marks of Each student of all subject: [63.333333333333336, 68.33333333333333, 45.666666666666664]
Student: 2  Scoured Maximum Average : 68.33333333333333
Student has improve highly in Math
